import {useEffect,useState} from 'react';
import {useLocation} from 'react-router-dom';
import {AnimatePresence,useReducedMotion} from 'motion/react';
import type {gsap as GsapType} from 'gsap';
import {PremiumToast} from './MotionUI';
export function SuccessDustEffect(rect:DOMRect,host:HTMLElement,gsap:typeof GsapType){const root=document.createElement('div');root.className='success-dust';root.setAttribute('aria-hidden','true');root.style.cssText=`position:fixed;left:${rect.left}px;top:${rect.top}px;width:${rect.width}px;height:${rect.height}px;pointer-events:none;z-index:9999;`;const check=document.createElement('b');check.textContent='✓';check.className='dust-check';root.append(check);const dots=Array.from({length:12},(_,i)=>{const dot=document.createElement('i');dot.style.cssText=`position:absolute;left:4px;top:${rect.height*.5}px;width:3px;height:3px;border-radius:50%;background:${i%2?'#b8ded4':'#65b8a3'};`;root.append(dot);return dot;});host.append(root);const timeline=gsap.timeline({onComplete:()=>root.remove()});timeline.fromTo(check,{opacity:0,scale:.8},{opacity:1,scale:1,duration:.12}).to(dots,{x:i=>-12-(i%4)*8,y:i=>(i-6)*4,opacity:0,stagger:.012,duration:.42,ease:'power2.out'},0).to(check,{opacity:0,duration:.2},.6);return ()=>{timeline.kill();root.remove();};}
export default function PremiumRuntime(){const {pathname}=useLocation();const reduced=useReducedMotion();const [toast,setToast]=useState<{text:string;tone:string}|null>(null);useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(null),3200);return()=>clearTimeout(timer);},[toast]);useEffect(()=>{let disposed=false;let candidate:{rect:DOMRect;at:number}|null=null;let cleanupDust:(()=>void)|undefined;const known=new WeakMap<Element,string>();let frame=0;const animations:Animation[]=[];
 const scope=document.querySelector('main');if(!scope)return;
 function scan(initial=false){scope!.querySelectorAll('.tl-notice,.tl-error,.transfer-feedback.saved').forEach(el=>{const text=el.textContent?.trim()||'';const prior=known.get(el);known.set(el,text);if(initial||!text||text===prior)return;const error=el.classList.contains('tl-error');setToast({text,tone:error?'error':/تم.*(حفظ|تأكيد|تسليم)|نجاح/.test(text)?'success':'info'});if(!error&&candidate&&Date.now()-candidate.at<2500&&/تم.*(حفظ|تأكيد|تسليم)|نجاح/.test(text)){if(!reduced){cleanupDust?.();const rect=candidate.rect;void import('gsap').then(({gsap})=>{if(!disposed)cleanupDust=SuccessDustEffect(rect,document.querySelector('dialog[open]')||document.body,gsap);});}candidate=null;}});}
 function click(e:Event){const b=(e.target as Element).closest('button');if(!b||b.disabled)return;if(/حفظ|تأكيد.*(تسليم|إغلاق|تسوية)/.test(b.textContent||''))candidate={rect:b.getBoundingClientRect(),at:Date.now()};else candidate=null;}
 function confirmed(event:Event){const text=(event as CustomEvent<string>).detail;setToast({text,tone:'success'});if(candidate&&!reduced){const rect=candidate.rect;void import('gsap').then(({gsap})=>{if(!disposed){cleanupDust?.();cleanupDust=SuccessDustEffect(rect,document.body,gsap);}});}candidate=null;}window.addEventListener('premium-success',confirmed);
 scan(true);const observer=new MutationObserver(()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>scan());});observer.observe(scope,{childList:true,subtree:true,characterData:true});scope.addEventListener('click',click,true);
 if(!reduced){scope.querySelectorAll('.stat-card,.tl-stats article,.quick-action,.settings-section').forEach((el,i)=>{if(i<24)animations.push(el.animate([{opacity:.4,transform:'translateY(6px)'},{opacity:1,transform:'translateY(0)'}],{duration:220,delay:Math.min(i*18,130)}));});}
 return()=>{disposed=true;window.removeEventListener('premium-success',confirmed);observer.disconnect();scope.removeEventListener('click',click,true);cancelAnimationFrame(frame);cleanupDust?.();animations.forEach(a=>a.cancel());};},[pathname,reduced]);return <AnimatePresence>{toast&&<PremiumToast key={toast.text} title={toast.tone==='success'?'تمت العملية':toast.tone==='error'?'راجع المدخلات':'إشعار'} description={toast.text} tone={toast.tone} close={()=>setToast(null)}/>}</AnimatePresence>;}


