import {useState} from 'react';
import {PageHeader} from '../components/ui';
import {FinanceRows,FinanceModal,FinanceDetails} from '../components/FinanceViews';
import {rateSeeds,currencyNames} from '../data/exchangeReportsMock';
import type {RateEntry} from '../data/exchangeReportsMock';
import './financePages.css';
import './cashbox.css';
const fmt=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:6}).format(n);
const blank={base:'',counter:'IQD',buy:'',sell:'',notes:''};
export default function ExchangeRates(){
 const [rates,setRates]=useState(rateSeeds);const [log,setLog]=useState<RateEntry[]>(rateSeeds);const [editing,setEditing]=useState<string|null>(null);const [history,setHistory]=useState<string|null>(null);const [v,setV]=useState(blank);const [error,setError]=useState('');const [updated,setUpdated]=useState('2026-09-05T18:00');
 function edit(r?:RateEntry){setEditing(r?.id||'new');setV(r?{base:r.base,counter:r.counter,buy:String(r.buy),sell:String(r.sell),notes:r.notes}:blank);setError('');}
 function save(){if(!v.base||!v.counter||v.base===v.counter||!Number.isFinite(Number(v.buy))||!Number.isFinite(Number(v.sell))||Number(v.buy)<=0||Number(v.sell)<=0||Number(v.sell)<Number(v.buy)){setError('اختر عملتين مختلفتين وأسعارًا موجبة؛ سعر البيع لا يقل عن الشراء.');return;}if(rates.some(r=>r.id!==editing&&r.base===v.base&&r.counter===v.counter)){setError('هذا الزوج موجود بالفعل؛ استخدم تعديل السعر.');return;}const now=new Date().toLocaleString('sv-SE');const r={...v,id:editing==='new'?crypto.randomUUID():editing!,buy:Number(v.buy),sell:Number(v.sell),user:'أحمد محمد',updated:now};setRates(old=>editing==='new'?[...old,r]:old.map(x=>x.id===editing?r:x));setLog(old=>[r,...old]);setUpdated(now);setEditing(null);}
 return <div className="finance-page"><nav className="breadcrumb">الصيرفة / أسعار الصرف</nav><PageHeader title="أسعار الصرف" description="عرض وإدارة الأسعار الاسترشادية المحلية."/><p className="tl-disclaimer">أسعار تجريبية فقط؛ التعديلات مؤقتة داخل هذه الصفحة.</p><div className="panel voucher-meta"><span>آخر تحديث للأسعار: {updated.replace('T',' ')}</span><button className="tl-button" onClick={()=>setUpdated(new Date().toLocaleString('sv-SE'))}>تحديث تجريبي</button><button className="tl-button primary" onClick={()=>edit()}>إضافة سعر جديد</button></div><div className="tl-stats">{rates.map(r=><article className="panel" key={r.id}><small>{currencyNames[r.base]}</small><h2 dir="ltr">{r.base} / {r.counter}</h2><FinanceDetails items={ [['سعر الشراء',fmt(r.buy)],['سعر البيع',fmt(r.sell)],['فرق السعر',fmt(r.sell-r.buy)],['آخر تحديث',r.updated.replace('T',' ')]]}/></article>)}</div><section className="panel voucher-section"><h2>جدول الأسعار</h2><FinanceRows headers={['العملة الأساسية','العملة المقابلة','سعر الشراء','سعر البيع','فرق السعر','المستخدم','آخر تحديث','الإجراءات']} rows={rates.map(r=>({id:r.id,cells:[r.base,r.counter,fmt(r.buy),fmt(r.sell),fmt(r.sell-r.buy),r.user,r.updated.replace('T',' '),<div className="tl-row-actions"><button className="tl-button" onClick={()=>edit(r)}>تعديل تجريبي</button><button className="tl-button" onClick={()=>setHistory(r.id)}>عرض السجل</button></div>]}))}/></section>{editing&&<FinanceModal title={editing==='new'?'إضافة سعر جديد':'تعديل السعر التجريبي'} close={()=>setEditing(null)}><form onSubmit={e=>{e.preventDefault();save();}} noValidate><div className="tl-edit-grid">{(['base','counter'] as const).map((k,i)=><label className="tl-field" key={k}><span>{i?'العملة المقابلة':'العملة'}</span><select aria-label={i?'العملة المقابلة':'العملة'} value={v[k]} onChange={e=>setV({...v,[k]:e.target.value})}><option value="">اختر</option>{Object.entries(currencyNames).map(([c,n])=><option key={c} value={c}>{c} · {n}</option>)}</select></label>)}{(['buy','sell'] as const).map((k,i)=><label className="tl-field" key={k}><span>{i?'سعر البيع':'سعر الشراء'}</span><input aria-label={i?'سعر البيع':'سعر الشراء'} type="number" step="any" value={v[k]} onChange={e=>setV({...v,[k]:e.target.value})}/></label>)}<label className="tl-field"><span>ملاحظات</span><textarea aria-label="ملاحظات" maxLength={1000} value={v.notes} onChange={e=>setV({...v,notes:e.target.value})}/></label></div>{error&&<p className="tl-error" role="alert">{error}</p>}<button className="tl-button primary">حفظ تجريبي</button></form></FinanceModal>}{history&&<FinanceModal title="سجل تغييرات السعر" close={()=>setHistory(null)}>{log.filter(r=>r.id===history).map((r,i)=><FinanceDetails key={i} items={ [['الزوج',`${r.base} / ${r.counter}`],['الشراء',fmt(r.buy)],['البيع',fmt(r.sell)],['المستخدم',r.user],['آخر تحديث',r.updated],['الملاحظات',r.notes||'—']]}/>)}</FinanceModal>}</div>;
}
