import {useState} from 'react';
import type {FormEvent} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {FinanceModal,FinanceDetails} from '../components/FinanceViews';
import {PageHeader} from '../components/ui';
import {registers,registerCurrencies,boxName} from '../data/cashRegistersMock';
import {exchangeRates} from '../data/dayExchangeMock';
import './financePages.css';
import './cashbox.css';
const fmt=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:6}).format(n);
const deviceTime=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,19);};
const initial={date:'',partyType:'عميل',party:'',currency:'USD',counter:'IQD',amount:'',rate:'',commission:'',box:'main',description:'',notes:''};
export default function ExchangeTrade({sell=false}:{sell?:boolean}) {
 const navigate=useNavigate(); const [v,setV]=useState(()=>({...initial,date:deviceTime(),rate:String(sell?1490:1480)})); const [id]=useState(()=>`DEMO-${sell?'SELL':'BUY'}-${crypto.randomUUID().slice(0,8)}`);
 const [error,setError]=useState(''); const [saved,setSaved]=useState(false); const [preview,setPreview]=useState(false);
 const title=sell?'بيع عملة':'شراء عملة';
 const amount=Number(v.amount)||0, rate=Number(v.rate)||0, commission=Number(v.commission)||0;
 const counterpart=amount*rate, total=counterpart+(sell?commission:-commission);

 const balance=registers.find(b=>b.id===v.box)?.balances[v.currency]||0;
 function change(k:keyof typeof initial,value:string){setV(old=>{const next={...old,[k]:value};if(k==='currency'||k==='counter'){const r=exchangeRates[`${next.currency}/${next.counter}`];next.rate=r?String(sell?r.sell:r.buy):'';}return next;});setSaved(false);setError('');}
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!v.party.trim()||!v.date||!Number.isFinite(Date.parse(v.date))||!registers.some(b=>b.id===v.box)||!registerCurrencies.includes(v.currency)||!registerCurrencies.includes(v.counter)){setError('الطرف والتاريخ والصندوق والعملتان مطلوبة.');return;}if(v.currency===v.counter){setError('اختر عملتين مختلفتين.');return;}if(!Number.isFinite(amount)||amount<=0||amount>1e12||!Number.isFinite(rate)||rate<=0||rate>1e6||!Number.isFinite(commission)||commission<0||commission>counterpart){setError('أدخل مبلغًا وسعرًا موجبين وعمولة بين صفر والمبلغ المقابل.');return;}setV(old=>({...old,date:deviceTime()}));setSaved(true);if((e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')==='print')setPreview(true);}
 function field(k:keyof typeof initial,label:string,type='text'){return <label className="tl-field"><span>{label}</span><input aria-label={label} type={type} step="any" maxLength={180} value={v[k]} onChange={e=>change(k,e.target.value)}/></label>;}
 function select(k:keyof typeof initial,label:string,options:{value:string;label:string}[]){return <label className="tl-field"><span>{label}</span><select aria-label={label} value={v[k]} onChange={e=>change(k,e.target.value)}><option value="">اختر</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;}
 const currencyOptions=registerCurrencies.map(c=>({value:c,label:c}));
 const details:[string,string][]=[['رقم العملية',id],['التاريخ والوقت',v.date],['نوع الطرف',v.partyType],['الطرف',v.party],['الصندوق',boxName(v.box)],[sell?'المبلغ المباع':'المبلغ المشترى',`${fmt(amount)} ${v.currency}`],[sell?'سعر البيع':'سعر الشراء',fmt(rate)],['المبلغ المقابل',`${fmt(counterpart)} ${v.counter}`],['العمولة',`${fmt(commission)} ${v.counter}`],['الإجمالي النهائي',`${fmt(total)} ${v.counter}`],['البيان',v.description||'—'],['الملاحظات',v.notes||'—']];
 return <div className="finance-page cash-voucher"><nav className="breadcrumb"><Link to="/dashboard">الرئيسية</Link><span> / الصيرفة / {title}</span></nav><PageHeader title={title} description={`${title} ${sell?'للعميل أو الشريك':'من العميل أو الشريك'} بمعاينة محلية واضحة.`}/><p className="tl-disclaimer">أسعار وبيانات تجريبية فقط. الحفظ داخل الصفحة ولا يغيّر أي رصيد.</p><div className="panel voucher-meta"><div><small>رقم العملية التجريبي</small><b dir="ltr">{id}</b></div><span className={`tl-badge ${saved?'done':'review'}`}>{saved?'محفوظ تجريبيًا':'مسودة'}</span></div><form noValidate onSubmit={submit}><section className="panel voucher-section"><h2>بيانات العملية</h2><div className="voucher-grid"><label className="tl-field"><span>التاريخ والوقت</span><input aria-label="التاريخ والوقت" type="datetime-local" step="1" readOnly value={v.date}/></label>{select('partyType','نوع الطرف',['عميل','شريك','أخرى'].map(c=>({value:c,label:c})))}{field('party','الطرف')}{select('currency',sell?'العملة المباعة':'العملة المشتراة',currencyOptions)}{field('amount','المبلغ','number')}{select('counter','العملة المقابلة',currencyOptions)}{field('rate',sell?'سعر البيع':'سعر الشراء','number')}{field('commission','العمولة إن وجدت','number')}{select('box','الصندوق',registers.map(b=>({value:b.id,label:b.name})))}{field('description','البيان')}<label className="tl-field voucher-notes"><span>الملاحظات</span><textarea aria-label="الملاحظات" rows={3} maxLength={1000} value={v.notes} onChange={e=>change('notes',e.target.value)}/></label></div></section><section className="panel voucher-section"><h2>معاينة العملية</h2><FinanceDetails items={details.slice(5,10)}/>{sell&&amount>balance&&<p className="voucher-warning" role="status">المبلغ أكبر من رصيد الصندوق ({fmt(balance)} {v.currency}). تحذير بصري فقط؛ الحفظ التجريبي متاح.</p>}</section>{error&&<p className="tl-error" role="alert">{error}</p>}{saved&&<p className="tl-notice" role="status">تم الحفظ التجريبي دون تغيير الأرصدة.</p>}<div className="panel voucher-actions"><button className="tl-button primary" value="save">حفظ تجريبي</button><button className="tl-button" value="print">حفظ وطباعة</button><button className="tl-button" type="button" onClick={()=>{setV({...initial,date:deviceTime(),rate:String(sell?1490:1480)});setError('');setSaved(false);}}>مسح</button><button className="tl-button" type="button" onClick={()=>navigate('/dashboard')}>إلغاء</button></div></form>{preview&&<FinanceModal title="معاينة إيصال الصيرفة" close={()=>setPreview(false)}><div className="voucher-print"><h2>إيصال {title} تجريبي</h2><p className="tl-disclaimer">نسخة توضيحية غير صالحة للتعامل المالي.</p><FinanceDetails items={details}/><button className="tl-button primary voucher-print-button" onClick={()=>window.print()}>طباعة الإيصال التجريبي</button></div></FinanceModal>}</div>;
}

