import {useState} from 'react';
import {saveCustomer,useCustomers} from '../data/customerRecords';
import type {Customer} from '../data/customerRecords';
import {PremiumButton} from './premium/MotionUI';
export default function CustomerForm({customer,onSaved,onCancel,comprehensive=false}:{customer?:Customer;comprehensive?:boolean;onSaved:()=>void;onCancel:()=>void}){
 const customers=useCustomers();const [draft,setDraft]=useState({name:customer?.name||'',phone:customer?.phone||'',address:customer?.address||'',notes:customer?.notes||''});const [error,setError]=useState('');const [saved,setSaved]=useState(false);
 const [balances,setBalances]=useState<Record<string,string>>(()=>Object.fromEntries(Object.entries(customer?.balances||{USD:0,IQD:0}).map(([code,value])=>[code,String(value)])));
 const [active,setActive]=useState(customer?.active??true);
 const code=customer?.id||`C-${Math.max(1000,...customers.map(c=>Number(c.id.slice(2))))+1}`;
 const [savedCode,setSavedCode]=useState('');
 return <form noValidate onSubmit={e=>{e.preventDefault();if(saved)return;const phone=draft.phone.trim().replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d)));if(!draft.name.trim()){setError('اسم العميل مطلوب.');return;}if(phone&&(!/^\+?[\d\s()-]+$/.test(phone)||phone.replace(/\D/g,'').length<7||phone.replace(/\D/g,'').length>15)){setError('أدخل هاتفًا صحيحًا من 7 إلى 15 رقمًا، أو اتركه فارغًا.');return;}if(comprehensive&&Object.values(balances).some(value=>!value.trim()||!Number.isFinite(Number(value))||Math.abs(Number(value))>1e12)){setError('أدخل أرصدة رقمية صحيحة بين سالب وموجب تريليون.');return;}if(!saveCustomer(customer?.id||null,{...draft,name:draft.name.trim(),phone,...(comprehensive?{active,balances:Object.fromEntries(Object.entries(balances).map(([code,value])=>[code,Number(value)]))}:{})}))return;setSavedCode(code);setSaved(true);setError('');onSaved();}}>
 <div className="tl-edit-grid"><label className="tl-field"><span>كود العميل</span><input aria-label="كود العميل" readOnly value={saved?savedCode:code}/></label>{(['name','phone','address','notes'] as const).map((key,i)=><label className="tl-field" key={key}><span>{['اسم العميل','رقم الهاتف','العنوان','ملاحظات'][i]}{key==='name'?' *':''}</span>{key==='notes'?<textarea aria-label="ملاحظات" maxLength={1000} rows={3} value={draft[key]} onChange={e=>{setDraft({...draft,[key]:e.target.value});setSaved(false);}}/>:<input aria-label={['اسم العميل','رقم الهاتف','العنوان'][i]} type={key==='phone'?'tel':'text'} required={key==='name'} maxLength={key==='phone'?25:160} value={draft[key]} onChange={e=>{setDraft({...draft,[key]:e.target.value});setSaved(false);}}/>}</label>)}</div>
 {comprehensive&&<section className="voucher-section"><h3>الأرصدة والحالة · تعديل محلي</h3><div className="tl-edit-grid">{Object.entries(balances).map(([code,value])=><label className="tl-field" key={code}><span>رصيد {code}</span><input aria-label={`رصيد ${code}`} type="number" step="any" value={value} onChange={e=>{setBalances({...balances,[code]:e.target.value});setSaved(false);}}/></label>)}<label className="tl-field"><span>حالة العميل</span><select aria-label="حالة العميل" value={active?'active':'disabled'} onChange={e=>{setActive(e.target.value==='active');setSaved(false);}}><option value="active">نشط</option><option value="disabled">معطل</option></select></label></div></section>}
 {error&&<p className="tl-error" role="alert">{error}</p>}<div className="tl-modal-actions"><PremiumButton type="submit" variant="primary" disabled={saved}>حفظ العميل</PremiumButton><PremiumButton type="button" onClick={()=>{setDraft({name:'',phone:'',address:'',notes:''});setError('');setSaved(false);}}>مسح</PremiumButton><PremiumButton type="button" onClick={onCancel}>إلغاء</PremiumButton></div></form>;
}
